### ISSUE TITLE
timeout overrides configured greater delay value

### ISSUE THREAD

**Issue by justwrote** [krasserm/streamz#56]
After some debugging I found out that specifying the timeout (https://github.com/krasserm/streamz/blob/master/streamz-camel-akka/src/main/scala/streamz/camel/akka/EndpointConsumer.scala#L52) will override the config `delay` (http://camel.apache.org/file2.html). This only happens if the `delay` value is greater than your 500ms timeout. Since we need a greater value it would be nice to have it removed at all and use the `receive(uri)` method (`delay` seems to have the same effect) or at least make it possible to change it. If you wish I'm happy to create a PR.

**Comment by krasserm** [comment]
Would appreciate a PR, thanks for offering. Maybe allowing applications to optionally place a config file (read by https://github.com/lightbend/config for example) would make most sense. Otherwise, several DSL methods would have to be extended in both, the camel-akka and camel-fs2, modules. Thoughts?
